### PR TITLE
added support to write contribs

### PR DESCRIPTION
**Pull request by NSEcho**
Hello, this PR references [issue #22](https://github.com/jubalh/gontributions/issues/22). It is adding option to save contributions at the file by saving Project.Name, Project.URL and Count inside the file in the format:
```
[2019-10-03 18:32:22] gontributions:https://github.com/jubalh/gontributions/:1
```
Also, option for config has been added as well.
This can further be made to show changes inside the file. For example, if the last time you had 5 contributions on specific project and in the time of running you have 7, to mark that line with something like **(CHANGES)**

### CODE REVIEW

**Comment by jubalh** [comment]
Thanks for your PR.
Actually I'm not sure how it relates to #22. 

Gontributions so far counts all your git/svn/hg contributions. To do so it downloads (backups) all repos you contributed to. And uses this then to recount all the contributions again.
So we have this saved and generating the reports also works offline or once the upstream repo went down.

But for Wikis we dont have this feature yet. If the wiki server disappears out contribs disappear. #22 was meant to save the counts of our edits in a certain wiki into a file. So what one needs to do is to create a new folder (like we have `repos-git` and `repos-debian` etc) called `wiki` and then have a file there with the name of the wiki. and in there save either the counts or the actual changes.

Also please read https://chris.beams.io/posts/git-commit/.

**Comment by NSEcho** [comment]
@jubalh alright, thanks for your reply. Will close this one and will make another PR once i finish it. Cheers

**Comment by jubalh** [comment]
Cool! Make sure to read **and** try https://github.com/jubalh/gontributions/blob/master/USAGE.md so that you understand how it works so far. And also to test your changes.

**Comment by NSEcho** [comment]
The funny thing is I read it, but missed the point of an issue lol

**Pull request closed without merging**
