### PR TITLE
Add fancy template

### PR DESCRIPTION
**Pull request by fbsb**

### CODE REVIEW

**Comment by fbsb** [comment]
Is there a way to use linked assets in the template like images or external stylesheets? At the moment the fancy template uses embedded css stylesheet.

**Comment by jubalh** [comment]
Awesome! Thanks!
Only a small mistake when there are multiple rows of tags, the area touches each other.

**Comment by fbsb** [comment]
@jubalh I fixed the tag margins

**Comment by jubalh** [comment]
@fabsb looks awesome! Thanks a lot!

**Pull request merged**
